{
 "title": "Overview",
 "time": { "from": "2025-09-13T14:05:00.000Z", "to": "2025-09-13T14:15:00.000Z" },
 "templating": {
  "list": [
   { "name": "run", "query": { "query": "label_values(run)" } },
   { "name": "rps", "query": { "query": "label_values(rps)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace((sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) * 100 / 2),\"name\",\"total\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_container",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace((rate(container_cpu_usage_seconds_total{name=\"backend\",image!=\"\"}[1m]) *100/2),\"name\",\"backend\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace((rate(container_cpu_usage_seconds_total{name=\"infra-consumer-1\",image!=\"\"}[1m]) *100/2),\"name\",\"consumer-1\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"infra-consumer-2\",image!=\"\"}[1m]) *100/2",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"infra-consumer-3\",image!=\"\"}[1m]) *100/2",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"kafka-1\",image!=\"\"}[1m]) *100/2",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"mysql\",image!=\"\"}[1m]) *100/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "요청 실패율",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(sum(k6_http_req_failed_rate),\"name\",\"http_req_failed_rate\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "네트워크 송신량/수신량",
   "type": "stat",
   "description": "mb 단위",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=~\"backend|infra-consumer-1|infra-consumer-2|infra-consumer-3|kafka-1|mysql|proxy\",image!=\"\"}/1000000",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_network_receive_bytes_total{name=~\"backend|infra-consumer-1|infra-consumer-2|infra-consumer-3|kafka-1|mysql|proxy\",image!=\"\"}/1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "프로듀서 vs 컨수머 처리 속도 비교",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"coupon-topic\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_oldest_offset{topic=\"coupon-topic\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "파티션 분산 상태",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"coupon-topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "timeseries",
   "description": "컨수머 입장에서 backlog \n컨수머가 아직 처리하지 못한 메시지 수\n0에 가까울 수록 메시지가 쌓이지 않고 거의 실시간으로 처리\n순간적으로 backlog가 어디에 생기는지(지연이 생기는 부분이 어디인지) 알 수 있음. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{consumergroup=\"coupon-consumer-group\"}",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "성공 요청 수 (k6)",
   "type": "timeseries",
   "description": "누적 성공 요청 수 : 전체 몇 건 처리됐나RPS(성공 요청 처리 속도) : 지금 처리율은 어떤가. 초당 몇 건을 처리했나.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(sum(k6_http_reqs_total{expected_response=\"true\",run=\"$run\",rps=\"$rps\"}),\"name\",\"누적 성공 요청 수\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(rate(k6_http_reqs_total{expected_response=\"true\", run=\"$run\", rps=\"$rps\"}[1m])),\"name\",\"RPS\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "가상 사용자 수 (k6)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(k6_vus{run=\"$run\",rps=\"$rps\"},\"name\",\"가상 사용자 수\",\"\",\"\")",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "토픽 처리량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"coupon-topic\"} - kafka_topic_partition_oldest_offset{topic=\"coupon-topic\"}",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "응답시간 (k6)",
   "type": "timeseries",
   "description": "ms 단위",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(\r\n  avg by(run, rps) (k6_http_req_duration_avg{run=\"$run\", rps=\"$rps\"}) * 1000,\r\n  \"name\", \"avg\", \"\", \"\"\r\n)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(\r\n  avg by(run, rps) (k6_http_req_duration_p95{run=\"$run\", rps=\"$rps\"}) * 1000,\r\n  \"name\", \"p95\", \"\", \"\"\r\n  \r\n)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "label_replace(\r\n  avg by(run, rps) (k6_http_req_duration_p99{run=\"$run\", rps=\"$rps\"}) * 1000,\r\n  \"name\", \"p99\", \"\", \"\"\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}