apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DJANGO_SETTINGS_MODULE: config.settings
  DB_HOST: mysql.app.svc.cluster.local
  DATABASE_URL: mysql://root:root@mysql.app.svc.cluster.local:3306/myapp
  KAFKA_BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  COUPON_ISSUE_TOPIC: random-coupon-topic
  JWT_ACCESS_MIN: "120"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/naanayoung/coupon-backend:latest
          envFrom:
            - configMapRef:
                name: backend-config
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: ghcr.io/naanayoung/coupon-backend:latest
          envFrom:
            - configMapRef:
                name: backend-config
          command:
            - python
            - manage.py
            - coupon_issue_consumer
            - --topic
            - random-coupon-topic
            - --group
            - coupon-consumer-group
            - --bootstrap
            - my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
